language: android
dist: trusty
jdk: openjdk11
android:
  components:
    # Uncomment the lines below if you want to
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-30.0.3

    # The SDK version used to compile your project
    - android-30

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository

    # Specify at least one system image,
    # if you need to run emulator(s) during your tests
    - sys-img-x86-android-30
before_install:
  - chmod +x gradlew
  - yes | $ANDROID_HOME/tools/bin/sdkmanager "platforms;android-30"
install:
  # Skip the default install stage
  - true
script:
  - ./gradlew assemble
